### ISSUE TITLE
Tracking Issue: Interactive Forms

### ISSUE THREAD

**Issue by tingerrr** [typst/pdf-writer#19]
# Description
This is a tracking issue for implementing interactive forms.

In order to support interactive forms with partial compliance to [PDF 1.7], pdf-writer must first support most of section 12.7 as well as a few other parts of the 1.7 spec which this section depends on. Certain features which are known to be deprecated in specs after 1.7, such as XFA forms, will not be implemented.

# Tasks
The following work has to be done, this list will be updated as new issues arise or feature sets are requested/dropped. Some of these features could later be dropped as optional or unneeded.

- [ ] #15
- [ ] Appearance streams (**12.5.5**)
- [ ] Widget Annotations (**12.5.6.19**)
- [ ] Support actions (**12.6**)
- [ ] Interactive Forms (**12.7**)
  - [ ] Interactive Form Dictionary (**12.7.2**)
    - [x] *requires* Resource Dictionary (**7.8.3**)
    - [ ] *requires* Trigger Events (**12.6.3**)
    - [ ] *requires* Widget Annotations (part of Annotation Dictionaries) (**12.5.6.19**)
  - [ ] Field Dictionaries (**12.7.3**)
  - [ ] Field Types (**12.7.4**)
    - [ ] Text fields (**12.7.4.2**)
    - [ ] Choice fields (**12.7.4.3**)
    - [ ] Button fields (**12.7.4.4**)
    - [ ] Signature fields (**12.7.4.5**)
  - [ ] Named Pages (**12.7.6**)
    - [ ] *requires* Named Dictionaries (**7.7.4**)
       - [ ] *requires* Name Trees (**7.9.6**)

# Motivation
The primary motivator is resolving https://github.com/typst/typst/issues/1765.

[PDF 1.7]: https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf

# Discussion
Please keep this issue clean of discussion, use any of the linked discussions or issues if need be. I will regularly update this PR and send a comment when that status changes or a feature set was completed.
